### ISSUE TITLE
Can't refresh successfully on a chat window

### ISSUE THREAD

**Issue by tylerharrison1188** [NullVoxPopuli/emberclear#81] opened 2019-05-20 13:24 UTC
**Device Info**: 
- MBP - Mac OS 10.14.4
- Chrome

**Repro steps**: 

- Open a chat window
- See that you can't hit "Send"
- Attempt a refresh
- See that your view doesn't refresh and you get the following error message in the console

> emberclear-66af73b144844aebf87ddcae367daabc.js:360 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at Object.setupIntersectionObserver (emberclear-66af73b144844aebf87ddcae367daabc.js:360)
    at Object.maybeSetupReadWatcher (emberclear-66af73b144844aebf87ddcae367daabc.js:358)
    at Object.didInsertElement (emberclear-66af73b144844aebf87ddcae367daabc.js:357)
    at Object.didCreateComponent (vendor-74d4d291859aa9c75c3bce10abd7f5dd.js:9160)
    at Object.didCreate (vendor-74d4d291859aa9c75c3bce10abd7f5dd.js:483)
    at Te.commit (vendor-74d4d291859aa9c75c3bce10abd7f5dd.js:2755)
    at at.commit (vendor-74d4d291859aa9c75c3bce10abd7f5dd.js:2764)
    at at.commit (vendor-74d4d291859aa9c75c3bce10abd7f5dd.js:343)
    at Wt._renderRoots (vendor-74d4d291859aa9c75c3bce10abd7f5dd.js:457)
    at Wt._renderRootsTransaction (vendor-74d4d291859aa9c75c3bce10abd7f5dd.js:462)<

**Comment by NullVoxPopuli** [comment] 2019-05-20 13:26
thanks! I need to come up with a way to securely / privately submit some info for reproduction efforts. hmm.

I believe this is specifically tied to either the length, size, or type of messages present in the chat window. 
I _may_ have a fix for this already in another branch, but I need to figure out a migration path to get there (data changes). _hmm_

**Comment by tylerharrison1188** [comment] 2019-09-14 15:50
Need to get access to MBP to re-test this. Will follow up with someone to test this.

**Comment by NullVoxPopuli** [comment] 2019-09-14 15:57
recently got access to browserstack things, so I'll be able to test all the scenarios :)

**Comment by NullVoxPopuli** [comment] 2019-11-12 11:54
Closing due to staleness. Can reopen if issue is still present.

**Closed by NullVoxPopuli** 2019-11-12 11:54 UTC
